export const comerciantes = [
  {
    nome: "Laticínios Boa Vida",
    sobre:
      "Produtos frescos e de qualidade diretamente da fazenda para sua mesa.",
    email: "laticinios@boavida.com",
    senha: "senha123",
    imagem: "boa_vida.jpg",
    relevancia: 95,
    data: "2024-05-10",
    produtos: [
      {
        nome: "Leite",
        descricao: "Leite fresco integral",
        preco: 3.5,
        quantidade: 200,
        marca: "Boa Vida",
        imagem: "leite.jpg",
        categoria: "Bebidas",
        id: 1,
      },
      {
        nome: "Queijo",
        descricao: "Queijo artesanal",
        preco: 25.0,
        quantidade: 50,
        marca: "Boa Vida",
        imagem: "queijo.jpg",
        categoria: "Laticínios",
        id: 2,
      },
      {
        nome: "Iogurte",
        descricao: "Iogurte natural",
        preco: 4.0,
        quantidade: 150,
        marca: "Boa Vida",
        imagem: "iogurte.jpg",
        categoria: "Bebidas",
        id: 3,
      },
    ],
  },
  {
    nome: "Padaria Pão Quente",
    sobre: "Delícias assadas diariamente para você começar bem o seu dia.",
    email: "padaria@paoconfete.com",
    senha: "senha456",
    imagem: "pao_quente.jpg",
    relevancia: 90,
    data: "2024-05-15",
    produtos: [
      {
        nome: "Pão Francês",
        descricao: "Pão francês fresquinho",
        preco: 0.5,
        quantidade: 300,
        marca: "Pão Quente",
        imagem: "pao_frances.jpg",
        categoria: "Padaria",
        id: 4,
      },
      {
        nome: "Croissant",
        descricao: "Croissant amanteigado",
        preco: 4.0,
        quantidade: 100,
        marca: "Pão Quente",
        imagem: "croissant.jpg",
        categoria: "Padaria",
        id: 5,
      },
      {
        nome: "Bolo de Cenoura",
        descricao: "Bolo de cenoura com cobertura de chocolate",
        preco: 25.0,
        quantidade: 20,
        marca: "Pão Quente",
        imagem: "bolo_cenoura.jpg",
        categoria: "Confeitaria",
        id: 6,
      },
    ],
  },
  {
    nome: "Hortifrúti Verde Vida",
    sobre:
      "Frutas, verduras e legumes fresquinhos direto do produtor para você.",
    email: "hortifruti@verdevida.com",
    senha: "senha789",
    imagem: "verde_vida.jpg",
    relevancia: 85,
    data: "2024-05-20",
    produtos: [
      {
        nome: "Maçã",
        descricao: "Maçã vermelha fresca",
        preco: 2.0,
        quantidade: 100,
        marca: "Verde Vida",
        imagem: "maca.jpg",
        categoria: "Hortifrúti",
        id: 7,
      },
      {
        nome: "Banana",
        descricao: "Banana nanica",
        preco: 1.5,
        quantidade: 200,
        marca: "Verde Vida",
        imagem: "banana.jpg",
        categoria: "Hortifrúti",
        id: 8,
      },
      {
        nome: "Cenoura",
        descricao: "Cenoura orgânica",
        preco: 3.0,
        quantidade: 150,
        marca: "Verde Vida",
        imagem: "cenoura.jpg",
        categoria: "Orgânicos",
        id: 9,
      },
    ],
  },
];
